### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by gildor** [arkanovicz/essential-kson#2]
It looks that the library is not published to Maven Central

**Comment by arkanovicz** [comment]
It is [published to Maven Central](https://central.sonatype.com/namespace/com.republicate.kson).

Maybe you did search for a Java artifact named `essential-kson.jar`. The correct artifact id is `essential-kson-jvm` for the JVM, all multiplaform libraries do require this suffix.

Full maven coordinates for the JVM facet:

```
<dependency>
    <groupId>com.republicate.kson</groupId>
    <artifactId>essential-kson-jvm</artifactId>
    <version>2.5</version>
</dependency>
```

**Comment by arkanovicz** [comment]
Oh, I see, the README has the wrong group! Fixing this right away.
